# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Run k6 - Functional Test in Cloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
      inputs:
       os_type:
         description: "Select OS to Run"
         required: true
         type: choice
         default: macOS-latest
         options:
           - macOS-latest
           - windows-latest
          
permissions:
  contents: read

jobs:
  my_first_job:
    name: Functional Test
    runs-on: ${{ github.event.inputs.os_type || 'macOS-latest' }}
    #strategy:
     #  matrix:
      #   os: ${{ inputs.os_type }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      #- name: debug
      - run:  echo "OS Version by biresh ${{ github.event.inputs.os_type }}"

      #- name: Install K6
       # run:  brew install k6

      - name: Install K6
        run:  brew install k6
        if: (github.event.inputs.os_type == 'macOS-latest')
      
      - name: K6 Version
        run: k6 --version
      
      - name: Run Functional Test
        run: k6 run functional_test/k6_functional_test.js
      
      - name: Download Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: functional-test-results
          path: results/functional_test_results
