# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Run k6 - Performance Test in Cloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
      inputs:
       os_type:
         description: "Select OS to Run"
         required: true
         type: choice
         default: macOS-latest
         options:
           - macOS-latest
           - windows-latest
          
permissions:
  contents: read

jobs:
  my_first_job:
    name: Performance Test
    runs-on: ${{ github.event.inputs.os_type || 'macOS-latest' }}
    #strategy:
     #  matrix:
      #   os: ${{ inputs.os_type }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Install K6 for no OS selected
        if: ${{ github.event.inputs.os_type == '' }}
        run: |
          echo "macOS installing..."
          brew install k6
      
      - name: Install K6 for Windows
        if: ${{ github.event.inputs.os_type == 'windows-latest' }}
        run: |
          echo "Windows installing..."
          choco install k6
      
      - name: Install K6 for macOS
        if: ${{ github.event.inputs.os_type == 'macOS-latest' }}
        run: |
          echo "macOS installing..."
          brew install k6
      
      - name: K6 Version
        run: k6 --version
      
      - name: Run Performance Test
        run: k6 run performance_test/k6_performance_test.js
      
      - name: Download Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-results
          path: results/performance_test_results
